
-- Total number of orders per month.
select order_month , count(*) as Total_orders
from pizza_sales
group by order_month;

-- Type of pizza with highest total quantity ordered
select pizza_category, count(pizza_category) AS pizza_type_with_highest_quantity
from pizza_sales
group by pizza_category
order by count(pizza_category) DESC LIMIT 1;

-- Size of pizza with highest total quantity ordered
select pizza_size, count(pizza_size) AS pizza_size_with_highest_quantity
from pizza_sales
group by pizza_size
order by count(pizza_size) DESC LIMIT 1;

-- Most common pizza size ordered for each pizza type. 
select pizza_category,pizza_size,count(*) AS Total_orders
from pizza_sales
group by pizza_category,pizza_size
order by pizza_category,Total_orders DESC;

-- Revenue generated for each pizza category.
select pizza_category , round(sum(total_price),2) AS total_revenue_generated
from pizza_sales
group by pizza_category
order by sum(total_price) DESC;

-- Average revenue per order
select round(AVG(total),2) AS avg_revenue_per_order
from ( select sum(total_price) as total
		from pizza_sales
        group by order_id) as order_revenue;

-- Distribution of orders by day of the week.
select dayname(order_date) as day_of_week , count(*) as total_count
from pizza_sales
group by day_of_week
order by day_of_week;


-- Distribution the category-wise distribution of pizza for each size.
select pizza_category , pizza_size , count(*)
from pizza_sales
group by pizza_category , pizza_size;

select * from pizza_sales;
select order_date,avg(total) as avg_revenue_per_day
 from ( select sum(total_price) as total
		from pizza_sales
        group by order_date) as daily_revenue;
        
-- Top 3 highest revenue generating pizza types for each pizza category.
select pizza_category , round(sum(total_price),3) as Total_price 
from pizza_sales
group by pizza_category
order by Total_price DESC LIMIT 3;

--  Percentage contribution of each pizza type of total revenue.
select pizza_category , round(sum(total_price) / ( select sum(total_price) from pizza_sales) * 100,2) AS revenue_percentage
from pizza_sales
group by pizza_category; 

-- Total revenue generated by each pizza size.
select pizza_size , round(sum(total_price),2) as total_price
from pizza_sales
group by pizza_size;

-- Total number of orders.
select count(*) as Total_orders
from pizza_sales;

-- Total revnue generated from pizza sales.
select round(sum(total_price),2) as Total_revnue_generated
from pizza_sales;

-- Highest priced pizza
select *
from pizza_sales
order by unit_price
DESC LIMIT 1	;
use dominos;


-- Most ordered pizza type along with thier quantity.
select pizza_size , count(order_id) AS Total_quantiy_ordered
from pizza_sales
group by pizza_size
order by Total_quantiy_ordered DESC;

-- Group the orders by date and calculate the average number of pizzas ordered per day.
select order_date , round(avg(order_id),0) as Average_pizza_ordered
from pizza_Sales
group by order_date;






